# Generated by Django 4.0 on 2023-06-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=500, verbose_name='Password'),
        ),
    ]
