# Generated by Django 4.0 on 2023-06-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0004_alter_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
