# Generated by Django 4.0 on 2023-06-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0005_remove_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='profilepics/', verbose_name='Profilpic'),
        ),
    ]
