# Generated by Django 4.0 on 2023-07-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0006_alter_user_profilepic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff')], default='Teacher', max_length=20),
        ),
    ]
